site_name: KassStorager
repo_url: https://github.com/kassiodouglas/KassStorager
repo_name: kassiodouglas/KassStorageras
edit_uri: tree/main/docs

theme: 
  name: material
  language: pt-BR

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [KassStorager]